# Generated by Django 2.2.12 on 2021-09-23 09:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='HL_1',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_10',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_11',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_12',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_13',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_14',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_15',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_16',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_17',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_18',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_19',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_2',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_20',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_21',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_22',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_23',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_25',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_26',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_27',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_28',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_29',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_3',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_30',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_4',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_5',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_6',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_7',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_8',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='HL_9',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
    ]
