# Generated by Django 2.2.12 on 2021-09-23 09:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_3', '0002_auto_20210923_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='HL_24',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
    ]
