# Generated by Django 2.2.12 on 2021-09-24 08:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_5', '0002_auto_20210923_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='w_amt',
            field=otree.db.models.FloatField(default=0, null=True, verbose_name=''),
        ),
    ]
