# Generated by Django 2.2.12 on 2021-09-24 08:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_5', '0003_player_w_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bin1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bin6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='w_amt',
        ),
        migrations.AddField(
            model_name='player',
            name='nbin1',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nbin2',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nbin3',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nbin4',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nbin5',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nbin6',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nw_amt',
            field=otree.db.models.FloatField(default=0, null=True, verbose_name=''),
        ),
    ]
