# Generated by Django 2.2.12 on 2021-09-24 07:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rHL_1',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_10',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_11',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_12',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_13',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_14',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_15',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_16',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_17',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_18',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_19',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_2',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_20',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_21',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_22',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_23',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_24',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_25',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_26',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_27',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_28',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_29',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_3',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_30',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_4',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_5',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_6',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_7',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_8',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rHL_9',
            field=otree.db.models.IntegerField(choices=[[1, 'A'], [2, 'B']], default=0, null=True),
        ),
    ]
