# Generated by Django 2.2.12 on 2021-09-22 14:42

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0002_player_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year_azienda',
            field=otree.db.models.IntegerField(null=True, verbose_name='1. Anno di nascita'),
        ),
    ]
