# Generated by Django 2.2.12 on 2021-09-22 14:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0004_auto_20210922_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='area',
            field=otree.db.models.IntegerField(null=True, verbose_name='5. Numero ettari (di proprietà e in affitto) gestiti dalla tua azienda'),
        ),
        migrations.AddField(
            model_name='player',
            name='areagrain',
            field=otree.db.models.IntegerField(null=True, verbose_name='5. Numero ettari coltivati a grano duro'),
        ),
        migrations.AddField(
            model_name='player',
            name='istruzione',
            field=otree.db.models.StringField(choices=[['1', 'Scuola elementare'], ['2', 'Scuola media'], ['3', 'Scuola secondaria'], ['4', 'Laurea'], ['5', 'Formazione post-laura']], max_length=10000, null=True, verbose_name='4. Livello di istruzione più alto'),
        ),
    ]
