# Generated by Django 2.2.12 on 2021-09-22 15:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0005_auto_20210922_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='businesstype',
            field=otree.db.models.StringField(choices=[['1', 'Specializzata in seminativi'], ['2', 'Mista colture'], ['3', 'Mista colture e allevamento']], max_length=10000, null=True, verbose_name='8. Tipologiaa azienda'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=otree.db.models.StringField(choices=[['1', 'Azienda individuale'], ['2', 'Società di persone'], ['3', 'Società di capitali'], ['4', 'Altro (specificare)']], max_length=10000, null=True, verbose_name='7. Forma giuridica dell azienda'),
        ),
        migrations.AddField(
            model_name='player',
            name='title',
            field=otree.db.models.StringField(choices=[['1', 'Coltivatore diretto'], ['2', 'IAP (imprenditore agricolo professionale'], ['3', 'Altro (specificare)']], max_length=10000, null=True, verbose_name='6. A che titolo svolgi attività agricola'),
        ),
    ]
