# Generated by Django 2.2.12 on 2021-09-22 15:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0006_auto_20210922_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q11',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='10. Nella tua azienda, hai già fatto uso di contratti di coltivazione nel corso degli ultimi 5 anni?'),
        ),
        migrations.AddField(
            model_name='player',
            name='revenue',
            field=otree.db.models.StringField(choices=[['1', 'Meno di 4.000 €'], ['2 ', 'Da 4.000 € a meno di 8.000 €'], ['3', 'Da 8.000 € a meno di 25.000 €'], ['4', 'Da 25.000 € a meno di 50.000 €'], ['5', 'Da 50.000 € a meno di 100.000 €'], ['6', 'Da 100.000 € a meno di 500.000 €'], ['7', 'Da 500.000 € a meno di 1.000.000 €']], max_length=10000, null=True, verbose_name='9. Fatturato medio annuo dell azienda'),
        ),
    ]
