# Generated by Django 2.2.12 on 2021-09-22 15:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0007_auto_20210922_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q10',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='10. Nella tua azienda, hai già fatto uso di contratti di coltivazione nel corso degli ultimi 5 anni?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q12',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='12. Prevedi che l azienda possa cambiare gestione nell arco dei prossimi anni? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q13',
            field=otree.db.models.StringField(choices=[['1', 'Sarà venduta a terzi'], ['2', 'Sarà gestita da un altro membro della famiglia (succesione)']], max_length=10000, null=True, verbose_name='13. Se si, prevedi che l azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q11',
            field=otree.db.models.StringField(choices=[['1', 'Meno di 5 anni'], ['2', 'Da 5 a 15 anni'], ['3', 'Più di 15 anni']], max_length=10000, null=True, verbose_name='4. Da quanti anni è presente l attuale conduzione aziendale?'),
        ),
    ]
