# Generated by Django 2.2.12 on 2021-09-22 16:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0008_auto_20210922_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q10',
        ),
        migrations.AddField(
            model_name='player',
            name='q14',
            field=otree.db.models.StringField(choices=[['1', 'Sarà venduta a terzi'], ['2', 'Sarà gestita da un altro membro della famiglia (succesione)']], max_length=10000, null=True, verbose_name='14. Se si, prevedi che l azienda'),
        ),
        migrations.AddField(
            model_name='player',
            name='q15',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='15. Hai mai fatto INVESTIMENTI IN AZIENDA (ammodernamento parco macchine, attrezzi, strutture aziendali) in passato? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q16',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='16. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q17',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='17. Hai mai STIPULATO CONTRATTI DI PRODUZIONE in passato? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q18',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='18. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q19',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='19. Hai mai CONTRATTO DEBITI (es. prestiti bancari) per la gestione dell azienda? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q20',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='20. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q21',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='21. Hai mai fatto ACCANTONAMENTI FINANZIARI nella tua azienda '),
        ),
        migrations.AddField(
            model_name='player',
            name='q22',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='22. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q23',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='23. Hai mai INTRODOTTO VARIETÀ INNOVATIVE in azienda in passato? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q24',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='24. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q25',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='25. Hai mai ADOTTATO L ASSICURAZIONE AGRICOLA in passato '),
        ),
        migrations.AddField(
            model_name='player',
            name='q26',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='26. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q27',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='27. Hai mai PRATICATO LA DIVERSIFICAZIONE (produttiva, attività connesse es. agriturismo,vendita aziendale) in azienda in passato? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q28',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='28. Intendi farlo in futuro?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q29',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='29. Hai mai fatto USO DELL IRRIGAZIONE in azienda in passato?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q30',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='30. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='q31',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='31. Hai mai ADOTTATO LA PRODUZIONE BIOLOGICA in azienda '),
        ),
        migrations.AddField(
            model_name='player',
            name='q32',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='32. Intendi farlo in futuro? '),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_1_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_2_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_3_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_4_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_5_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_6_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_a',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_b',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_c',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_d',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_e',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_g',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_h',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_i',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_m',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_n',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_o',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_p',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_q',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_r',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_s',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tab_7_t',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='areagrain',
            field=otree.db.models.IntegerField(null=True, verbose_name='6. Numero ettari coltivati a grano duro'),
        ),
        migrations.AlterField(
            model_name='player',
            name='businesstype',
            field=otree.db.models.StringField(choices=[['1', 'Specializzata in seminativi'], ['2', 'Mista colture'], ['3', 'Mista colture e allevamento']], max_length=10000, null=True, verbose_name='9. Tipologiaa azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q11',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='11. Nella tua azienda, hai già fatto uso di contratti di coltivazione nel corso degli ultimi 5 anni?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q12',
            field=otree.db.models.StringField(choices=[['1', 'Meno di 5 anni'], ['2', 'Da 5 a 15 anni'], ['3', 'Più di 15 anni']], max_length=10000, null=True, verbose_name='12. Da quanti anni è presente l attuale conduzione aziendale?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q13',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='13. Prevedi che l azienda possa cambiare gestione nell arco dei prossimi anni? '),
        ),
        migrations.AlterField(
            model_name='player',
            name='revenue',
            field=otree.db.models.StringField(choices=[['1', 'Meno di 4.000 €'], ['2 ', 'Da 4.000 € a meno di 8.000 €'], ['3', 'Da 8.000 € a meno di 25.000 €'], ['4', 'Da 25.000 € a meno di 50.000 €'], ['5', 'Da 50.000 € a meno di 100.000 €'], ['6', 'Da 100.000 € a meno di 500.000 €'], ['7', 'Da 500.000 € a meno di 1.000.000 €']], max_length=10000, null=True, verbose_name='10. Fatturato medio annuo dell azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=otree.db.models.StringField(choices=[['1', 'Azienda individuale'], ['2', 'Società di persone'], ['3', 'Società di capitali'], ['4', 'Altro (specificare)']], max_length=10000, null=True, verbose_name='8. Forma giuridica dell azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=otree.db.models.StringField(choices=[['1', 'Coltivatore diretto'], ['2', 'IAP (imprenditore agricolo professionale'], ['3', 'Altro (specificare)']], max_length=10000, null=True, verbose_name='7. A che titolo svolgi attività agricola'),
        ),
    ]
