# Generated by Django 2.2.12 on 2021-09-22 16:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0010_player_qc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='qc1',
            field=otree.db.models.StringField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7']], max_length=10000, null=True, verbose_name=''),
        ),
    ]
