# Generated by Django 2.2.12 on 2021-09-22 16:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0013_auto_20210922_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='qc2',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc3',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc4',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc5',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc6',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc7',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc8',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='qc9',
            field=otree.db.models.StringField(choices=[['1', ''], ['2', ''], ['3', ''], ['4', ''], ['5', ''], ['6', ''], ['7', '']], max_length=10000, null=True, verbose_name=''),
        ),
    ]
