# Generated by Django 2.2.12 on 2021-09-27 15:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0016_auto_20210924_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='businesstype',
            field=otree.db.models.StringField(choices=[['1', 'Specializzata in seminativi'], ['2', 'Mista colture'], ['3', 'Mista colture e allevamento']], max_length=10000, null=True, verbose_name='9. Tipologia della tua azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q12',
            field=otree.db.models.StringField(choices=[['1', 'Meno di 5 anni'], ['2', 'Da 5 a 15 anni'], ['3', 'Più di 15 anni']], max_length=10000, null=True, verbose_name='12. Da quanti anni è presente la attuale conduzione aziendale?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q13',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='13. Prevedi che la tua azienda possa cambiare gestione nell arco dei prossimi anni? '),
        ),
        migrations.AlterField(
            model_name='player',
            name='revenue',
            field=otree.db.models.StringField(choices=[['1', 'Meno di 4.000 €'], ['2 ', 'Da 4.000 € a meno di 8.000 €'], ['3', 'Da 8.000 € a meno di 25.000 €'], ['4', 'Da 25.000 € a meno di 50.000 €'], ['5', 'Da 50.000 € a meno di 100.000 €'], ['6', 'Da 100.000 € a meno di 500.000 €'], ['7', 'Da 500.000 € a meno di 1.000.000 €']], max_length=10000, null=True, verbose_name='10. Fatturato medio annuo della tua azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=otree.db.models.StringField(choices=[['1', 'Azienda individuale'], ['2', 'Società di persone'], ['3', 'Società di capitali'], ['4', 'Altro (specificare)']], max_length=10000, null=True, verbose_name='8. Forma giuridica della tua azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=otree.db.models.StringField(choices=[['1', 'Coltivatore diretto'], ['2', 'IAP (imprenditore agricolo professionale'], ['3', 'Altro (specificare)']], max_length=10000, null=True, verbose_name='7. A che titolo svolgi la tua attività agricola'),
        ),
    ]
