# Generated by Django 2.2.12 on 2021-09-27 15:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0017_auto_20210927_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q29',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='29. Hai mai fatto USO DI SISTEMI DI IRRIGAZIONE in azienda in passato?'),
        ),
    ]
