# Generated by Django 2.2.12 on 2021-09-27 16:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0018_auto_20210927_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q23',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='23. Hai mai INTRODOTTO VARIETÀ INNOVATIVE in azienda in passato?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q24',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='24. Intendi farlo in futuro?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q26',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='26. Intendi farlo in futuro?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q27',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='27. Hai mai PRATICATO LA DIVERSIFICAZIONE (produttiva, attività connesse es. agriturismo,vendita aziendale) in azienda in passato?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q31',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='31. Hai mai ADOTTATO LA PRODUZIONE BIOLOGICA in azienda? '),
        ),
    ]
