# Generated by Django 2.2.12 on 2021-09-27 16:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_7', '0019_auto_20210927_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q13',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='13. Prevedi che la tua azienda possa cambiare gestione nell arco dei prossimi anni?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q14',
            field=otree.db.models.StringField(choices=[['1', 'Sarà venduta a terzi'], ['2', 'Sarà gestita da un altro membro della famiglia (succesione)']], max_length=10000, null=True, verbose_name='14. SE SI, prevedi che la tua azienda'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q15',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='15. Hai mai fatto INVESTIMENTI IN AZIENDA (ammodernamento parco macchine, attrezzi, strutture aziendali) in passato?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q16',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='16. Intendi farlo in futuro?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q17',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='17. Hai mai STIPULATO CONTRATTI DI PRODUZIONE in passato?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q18',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='18. Intendi farlo in futuro?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q19',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='19. Hai mai CONTRATTO DEBITI (es. prestiti bancari) per la gestione dell azienda?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q20',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='20. Intendi farlo in futuro?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q21',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='21. Hai mai fatto ACCANTONAMENTI FINANZIARI nella tua azienda?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q22',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='22. Intendi farlo in futuro?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q25',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='25. Hai mai ADOTTATO LA ASSICURAZIONE AGRICOLA in passato?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q31',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='31. Hai mai ADOTTATO LA PRODUZIONE BIOLOGICA in azienda?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='q32',
            field=otree.db.models.StringField(choices=[['1', 'SI'], ['2', 'NO']], max_length=10000, null=True, verbose_name='32. Intendi farlo in futuro?'),
        ),
    ]
