# Generated by Django 2.2.12 on 2021-09-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sezione_1', '0002_auto_20210922_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tab_8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tab_9',
        ),
    ]
